---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    hostname: sambaserver
    image: geerlingguy/docker-debian11-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    cgroupns_mode: host
    privileged: true
    tty: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
